#!/usr/bin/env bash

# Clean Triton cache.
rm -rf ~/.triton/cache

# Remove artifacts from previous executions.
rm -rf gmm_agent_info.csv gmm_kernel_trace.csv

# Run rocprof.
rocprofv3 \
    --kernel-trace --truncate-kernels \
    --output-format csv --output-file gmm \
    -- python test_gmm.py &> /dev/null

# Process CSV file generated by rocprof.
python<<EOF
import pandas as pd
# Read CSV file.
df = pd.read_csv(
    "gmm_kernel_trace.csv", usecols=["Kernel_Name", "Start_Timestamp", "End_Timestamp"]
)
# Filter by kernel name.
df = df[
    (df["Kernel_Name"] == "_grouped_bf16_persistent_gemm_kernel")
    | (df["Kernel_Name"] == "gmm_kernel")
]
# Keep only the last 20 samples per kernel. Other samples are test and warmup runs.
df = df.groupby("Kernel_Name", as_index=False).tail(20)
# Compute execution time in milliseconds.
df["Time_ms"] = (df["End_Timestamp"] - df["Start_Timestamp"]) * 1e-6
# Drop timestamps.
df = df[["Kernel_Name", "Time_ms"]]
# Rename kernels.
df["Kernel_Name"] = df["Kernel_Name"].replace(
    {"_grouped_bf16_persistent_gemm_kernel": "Primus-Turbo", "gmm_kernel": "AITER"}
)
# Compute statistics per kernel.
stats = (
    df.groupby("Kernel_Name")["Time_ms"]
    .agg(min=("min"), average=("mean"), max=("max"))
    .round(4)
)
# Print stats.
print(stats)
EOF
